#!/bin/bash
eval "$(~/.local/bin/mise activate bash)"
export PATH="$HOME/.pixi/bin:$PATH"
export EDITOR=nvim

alias t='SHELL=$(which zsh) tmux new -As home'

if [  "`which tmux`" ] && [ "`which zsh`" ]  && [ "$TMUX" == "" ]; then
	t
fi
