[tools]
neovim = "latest"
fzf = "latest"
node = "latest"
tmux = "latest"
bat = "latest"
jq =  "latest"
dvc = "latest"
gh = "latest"
aws-cli = "latest"
chezmoi = "latest"
glab = "latest"
fd = "latest"
yq = "latest"
pixi = "latest"
ripgrep = "latest"
ruff = "latest"
lazygit = "latest"
lazydocker = "latest"
