channels:
  - conda-forge
  - quentinf00
dependencies:
  - pip
  - pyright
  - tree
  - visidata
  - fd-find=8.2
  - tmux=3.1
  # - vim=8.2
  # - git=2.30
  - perl=5.32.1
  - fzf=0.27.2
  - ripgrep=13.0
  - bat=0.18
  - zsh=5.6
  - pip:
    - tmuxp
    - tldr
    - thefuck
